### ISSUE TITLE
Set is no more Swift 2-compatible as of beta 4

### ISSUE THREAD

**Issue by madbat** [robrix/Set#58]
Changes to the Swift standard library in Swift 2.0-beta4 (i.e. ExtensibleCollectionType -> RangeReplaceableCollectionType) prevent Multiset from compiling.

Unfortunately I don't feel confident enough with the implementation to try addressing the problem myself :persevere:

**Comment by robrix** [comment]
Yikes. This one looks like fun :confused: Thanks for the issue. Not :100:% sure how to implement `replaceRange` just yet; `MultisetIndex` is a bit weird, and since `Dictionary` and `Set` aren’t `RangeReplaceableCollectionType`s, there are likely some rocks under the surface.

We may want to just forego `RangeReplaceableCollectionType` altogether, honestly, and overload `+=` (which is all that `ExtensibleCollectionType` was really buying us).

**Comment by madbat** [comment]
It makes sense to me!
